version: '3.3'

services:
  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    ports:
      - "8080:8080"
    environment:
      - ATL_DB_TYPE=h2
      - ATL_JDBC_URL=jdbc:h2:mem:jiradb;DB_CLOSE_DELAY=-1
      - ATL_JDBC_USER=sa
      - ATL_JDBC_PASSWORD=sa
    volumes:
      - jira_data:/var/atlassian/application-data/jira  # Ensure data persistence

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: confluencedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  confluence:
    image: atlassian/confluence-server:latest
    container_name: confluence
    ports:
      - "8090:8090"
    environment:
      - ATL_DB_TYPE=postgresql
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/confluencedb
      - ATL_JDBC_USER=confluence
      - ATL_JDBC_PASSWORD=confluence_pass
    depends_on:
      - db
    volumes:
      - confluence_data:/var/atlassian/application-data/confluence




  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      - JENKINS_USER=admin
      - JENKINS_PASS=admin_password
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jira_data:
  confluence_data:
  jenkins_home:
  postgres_data:
